# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 372a013e799a5db911e9b158d7685c26e479da702305a15946fa40cb018a5107e3285b9eca5b64af3933d561ac36e4b05fc981da46d5180b741b785aebcb5236

test:
  secret_key_base: 782b90bf980e3f40af3bd8b7cc873dcce62d8466becfe69607367fbdae976d516c7657a80ec28d1ad4c7697a76ac25abfacdfa871581feb733d4d104af50979b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
